DouglasHalse/snackAttackTrack

- GuiApp/main.py
- README.md
This will be helpful when creating new pages/widgets
> Enable kivy inspector for layout debugging

- GuiApp/database.py
- GuiApp/main.py
This will be fine for a few database tables, if more is added in the future then more refactoring is needed.
> Add snacks and payment database tables

- README.md
> Removed reference to mosquitto requirements in readme and also fixed markdown lint violations.

- .pre-commit-config.yaml
- GuiApp/database.py
- GuiApp/main.py
- GuiApp/widgets/baseDevice.py
- GuiApp/widgets/deviceRow.py
- GuiApp/widgets/emfReader.py
- GuiApp/widgets/genericDevice.py
- GuiApp/widgets/loginScreen.py
- GuiApp/widgets/patronRow.py
- GuiApp/widgets/popups/abortPopup.py
- GuiApp/widgets/popups/addPatronPopup.py
- GuiApp/widgets/popups/errorMessagePopup.py
- GuiApp/widgets/popups/manageDevicePopup.py
- GuiApp/widgets/popups/managePatronsPopup.py
- GuiApp/widgets/snackAttackTrack.py
- GuiApp/widgets/splashScreen.py
- README.md
- requirements.txt
If we want to have some form of code standard and code formatting. I have disabled some checks that should be re-enabled once we decide which widgets should be kept and which ones should not.
> Running pylint on widgets code

- .github/workflows/pre-commit.yml
This pr enables pre-commit checks to run on github
> Create pre-commit.yml for github workflow

- GuiApp/kv/createUserScreen.kv
- GuiApp/kv/main.kv
- GuiApp/main.py
- GuiApp/widgets/createUserScreen.py
- GuiApp/widgets/loginScreen.py
Add create new user page
closes #18
> Add create new user page

- GuiApp/kv/aboutPopup.kv
> added name to the AboutPopup in the .kv file

- GuiApp/database.py
- GuiApp/kv/adminScreen.kv
- GuiApp/kv/editSnacksScreen.kv
- GuiApp/kv/headerBodyLayout.kv
- GuiApp/kv/main.kv
- GuiApp/kv/mainUserScreen.kv
- GuiApp/main.py
- GuiApp/widgets/adminScreen.py
- GuiApp/widgets/editSnacksScreen.py
- GuiApp/widgets/headerBodyLayout.py
- GuiApp/widgets/loginScreen.py
- GuiApp/widgets/mainUserScreen.py
> Add edit snacks screen

- GuiApp/database.py
- GuiApp/kv/editUsersScreen.kv
- GuiApp/kv/main.kv
- GuiApp/main.py
- GuiApp/widgets/adminScreen.py
- GuiApp/widgets/editUsersScreen.py
- GuiApp/widgets/loginScreen.py
Add a ugly edit users screen, but it works. 
close #34
> Add edit users screen

- GuiApp/widgets/addSnackScreen.py
- GuiApp/widgets/adminScreen.py
- GuiApp/widgets/editSnacksScreen.py
- GuiApp/widgets/editUsersScreen.py
- GuiApp/widgets/headerBodyLayout.py
- GuiApp/widgets/mainUserScreen.py
- GuiApp/widgets/topUpAmountScreen.py
- GuiApp/widgets/topUpPaymentScreen.py
Makes the gui way more responsive
> Load screens before transition

- GuiApp/database.py
- GuiApp/kv/buyScreen.kv
- GuiApp/kv/main.kv
- GuiApp/main.py
- GuiApp/widgets/buyScreen.py
- GuiApp/widgets/mainUserScreen.py
> Add buy screen

- .github/workflows/VisualDiff.yml
- .github/workflows/scripts/diffImages.py
- .github/workflows/scripts/diffImages.sh
- .vscode/launch.json
- GuiApp/getImages.py
- GuiApp/main.py
- requirements.txt
- runGetImages.sh
_Should_ work after this is merged for new PRs
> Add visual diff action

- GuiApp/database.py
- GuiApp/kv/historyScreen.kv
- GuiApp/kv/main.kv
- GuiApp/main.py
- GuiApp/widgets/buyScreen.py
- GuiApp/widgets/editUserScreen.py
- GuiApp/widgets/historyScreen.py
- GuiApp/widgets/mainUserScreen.py
- GuiApp/widgets/topUpPaymentScreen.py
https://github.com/user-attachments/assets/9738c5c6-896a-4949-8f37-ae99749c5a15
> Add history screen

- GuiApp/database.py
- GuiApp/getImages.py
- GuiApp/kv/editSnackScreen.kv
- GuiApp/kv/main.kv
- GuiApp/main.py
- GuiApp/widgets/customScreenManager.py
- GuiApp/widgets/editSnackScreen.py
- GuiApp/widgets/editSnacksScreen.py
- GuiApp/widgets/editUserScreen.py
https://github.com/user-attachments/assets/ad79c064-236c-4f7f-914e-e9c8e7bced57
> Add edit snack screen

- GuiApp/kv/main.kv
- GuiApp/kv/purchaseCompletedPopup.kv
- GuiApp/widgets/buyScreen.py
- GuiApp/widgets/popups/purchaseCompletedPopup.py
https://github.com/user-attachments/assets/66a30c87-7b90-402b-8bad-034cb6d28ce8
> Add purchase complete animation

- GuiApp/kv/main.kv
- GuiApp/kv/purchaseSummaryPopup.kv
- GuiApp/widgets/buyScreen.py
- GuiApp/widgets/historyScreen.py
- GuiApp/widgets/popups/purchaseSummaryPopup.py
https://github.com/user-attachments/assets/a0cb312e-f94d-4575-95b3-4639768bb405
> Add purchase summary

- GuiApp/kv/editSummaryPopup.kv
- GuiApp/kv/main.kv
- GuiApp/kv/purchaseSummaryPopup.kv
- GuiApp/widgets/historyScreen.py
- GuiApp/widgets/popups/editSummaryPopup.py
https://github.com/user-attachments/assets/3f7f4cdf-27d8-4943-9289-add962a07259
> Add edit summary

- GuiApp/kv/main.kv
- GuiApp/kv/topUpSummaryPopup.kv
- GuiApp/widgets/historyScreen.py
- GuiApp/widgets/popups/topUpSummaryPopup.py
> Add top up summary

- GuiApp/kv/addSnackScreen.kv
- GuiApp/kv/createUserScreen.kv
- GuiApp/kv/editSnackScreen.kv
- GuiApp/kv/editUserScreen.kv
- GuiApp/kv/headerBodyLayout.kv
- GuiApp/kv/main.kv
- GuiApp/kv/uiElements/buttons.kv
- GuiApp/kv/uiElements/textInputs.kv
- GuiApp/main.py
- GuiApp/widgets/addSnackScreen.py
- GuiApp/widgets/createUserScreen.py
- GuiApp/widgets/editSnackScreen.py
- GuiApp/widgets/editUserScreen.py
- GuiApp/widgets/uiElements/buttons.py
- GuiApp/widgets/uiElements/textInputs.py
I did some layout changes to the create user screen too
> Create generic textinput

- GuiApp/kv/buyScreen.kv
- GuiApp/kv/clickableTable.kv
- GuiApp/kv/headerBodyLayout.kv
- GuiApp/kv/loginScreen.kv
- GuiApp/kv/purchaseSummaryPopup.kv
- GuiApp/widgets/buyScreen.py
- GuiApp/widgets/clickableTable.py
- GuiApp/widgets/editSnacksScreen.py
> Create scrolling table columns

- GuiApp/kv/creditsAnimationPopup.kv
- GuiApp/kv/main.kv
- GuiApp/widgets/buyScreen.py
- GuiApp/widgets/popups/creditsAnimationPopup.py
- GuiApp/widgets/topUpPaymentScreen.py
https://github.com/user-attachments/assets/9f569015-1af8-459b-b081-0c5e1656cc1b
> Add top up animation

- .gitignore
Negations need to go last in gitignore file in order so it is correctly parsed
> chore(dev env): 🔧 gitignore put negations last

- .vscode/extensions.json
- .vscode/settings.json
Add recommended extensions to VS Code workspace
> chore(dev env): :wrench: Add recommended vscode extensions

- README.md
Made the README look a bit better with some markdown formatting
> docs: :memo: Update README formatting

- .vscode/settings.json
Add scope "app" to VS Code settings for conventional commits
> chore(dev env): :wrench: add scope to vscode settings

- GuiApp/kv/splashScreen.kv
> chore: :wrench: Adjust layout and spacing in splash screen for 1280 x 800

- GuiApp/kv/headerBodyLayout.kv
https://github.com/user-attachments/assets/91925ceb-4bb5-49c0-8dfe-632fcd90bd89
> chore(app): 🎨 enhance layout and spacing in header body layout for 1280 x 800
